version: "3.8"
services:
  app:
    image: jbaczuk/docker-nextjs
    networks:
      - default
      - localmongo
    external_links:
      - localmongo1:mongo1
      - localmongo2:mongo2
      - localmongo3:mongo3
    ports:
      - '3000:3000'
networks:
  localmongo:
    external:
      name: localmongo_default